language: ruby
rvm:
  - "2.1.10"
  - "2.2.5"
  - "2.3.1"
  - "2.4.0"
  # Temporarily disable the ruby-head build due to gem extension issue
  - "ruby-head"
  #- rbx-2
  #- rbx-3
  #- jruby-9.0.0.0
  #- jruby-9.0.1.0
  #- jruby-9.0.4.0
  #- jruby-9.0.5.0
  #- jruby-head
sudo: required
dist: trusty
before_install: gem update --system
install: ./travis/install-dependencies.sh
before_script: ./travis/clear-port-53.sh
script: bundle exec rspec spec
addons:
  code_climate:
    repo_token: d8cb42815dd1076748cb239c298cd700d96c5a1b4aefa7ae340c6701050b6432
